[package]
version = "0.1.0"
name = "log0-program"
edition = "2021"

[dependencies]
alloy-sol-types.workspace = true
sp1-zkvm.workspace = true
log0-summer-lib.workspace = true
reth-primitives.workspace = true
